from typing import Protocol, Any


class IDefenderProvider(Protocol):
    async def query_defender_status(self, device_hostname: str) -> dict[str, Any]: ...
    async def query_device_onboarding(self) -> dict[str, Any]: ...
    async def query_threat_alerts(self, severity: str | None = None) -> list[dict[str, Any]]: ...
    async def query_device_risk_score(self, device_hostname: str) -> dict[str, Any]: ...
    async def query_signature_status(self) -> dict[str, Any]: ...