from typing import Protocol, Any


class IRemoteAccessProvider(Protocol):
    async def query_vpn_policy(self, device_hostname: str) -> dict[str, Any]: ...
    async def configure_cached_credentials(self, policy: dict[str, Any]) -> dict[str, Any]: ...
    async def query_vpn_gateway_status(self) -> list[dict[str, Any]]: ...
    async def query_conditional_access_policies(self) -> list[dict[str, Any]]: ...
    async def configure_hybrid_join(self, config: dict[str, Any]) -> dict[str, Any]: ...
    async def query_device_classification_policy(self) -> list[dict[str, Any]]: ...
    async def query_dc_isolation_policy(self) -> dict[str, Any]: ...
    async def configure_dc_isolation(self, policy: dict[str, Any]) -> dict[str, Any]: ...
    async def update_vpn_credentials(self, user_account: str) -> dict[str, Any]: ...
    async def trigger_gpo_update(self, target_ou: str, computer_list: list[str]) -> dict[str, Any]: ...
    async def enable_bitlocker_remotely(self, computer_name: str) -> dict[str, Any]: ...
    async def rotate_bitlocker_recovery_key_remotely(self, computer_name: str) -> dict[str, Any]: ...