from typing import Protocol, Any


class IVpnProvider(Protocol):
    async def query_gateway_status(self) -> list[dict[str, Any]]: ...
    async def query_sessions(self, filters: dict[str, Any] | None = None) -> list[dict[str, Any]]: ...
    async def query_device_tunnel_status(self, device_hostname: str) -> dict[str, Any]: ...
    async def query_user_tunnel_status(self, user_account: str) -> dict[str, Any]: ...
    async def query_kerberos_recovery_status(self, user_account: str) -> dict[str, Any]: ...
    async def query_audit_log(self, filters: dict[str, Any] | None = None) -> list[dict[str, Any]]: ...
    async def update_vpn_policy(self, policy_type: str, config: dict[str, Any]) -> dict[str, Any]: ...